-- RT Crackers database-driven theme system.
-- Applied to project: ypmiinmkyvzdpakbkers
-- One row per website/page. Admin writes are protected by private.is_admin().

create table if not exists public.theme_page_settings (
  theme_page_id bigint generated by default as identity primary key,
  website_key text not null,
  page_key text not null,
  page_name text not null,
  is_active boolean not null default true,
  mode text not null default 'light' check (mode in ('light','dark','system')),
  background_color text not null default '#fff8f5',
  surface_color text not null default '#fffaf7',
  surface_elevated_color text not null default '#ffffff',
  section_color text not null default '#fff1ec',
  header_color text not null default '#ffffff',
  footer_color text not null default '#3a0808',
  text_color text not null default '#241716',
  muted_text_color text not null default '#756a67',
  heading_color text not null default '#c92b26',
  primary_color text not null default '#d92d27',
  primary_dark_color text not null default '#a91f1b',
  secondary_color text not null default '#7b4cc7',
  accent_color text not null default '#e7ad21',
  link_color text not null default '#b72b26',
  button_background_color text not null default '#d92d27',
  button_text_color text not null default '#ffffff',
  border_color text not null default '#ead8d1',
  border_strong_color text not null default '#d9bcb3',
  input_background_color text not null default '#ffffff',
  input_border_color text not null default '#decac3',
  card_shadow_color text not null default 'rgba(80,20,15,.10)',
  hero_background_color text not null default '#fff2dc',
  banner_background_color text not null default '#fff0e9',
  nav_background_color text not null default '#ffffff',
  nav_text_color text not null default '#241716',
  font_heading text not null default 'system-ui',
  font_body text not null default 'system-ui',
  radius_small text not null default '10px',
  radius_medium text not null default '16px',
  radius_large text not null default '24px',
  component_tokens jsonb not null default '{}'::jsonb,
  custom_css jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (website_key,page_key)
);

create index if not exists idx_theme_page_settings_website on public.theme_page_settings(website_key,is_active);
alter table public.theme_page_settings enable row level security;
revoke all on public.theme_page_settings from anon, authenticated;
grant select on public.theme_page_settings to anon, authenticated;
grant select,insert,update,delete on public.theme_page_settings to authenticated;
drop policy if exists theme_public_read on public.theme_page_settings;
create policy theme_public_read on public.theme_page_settings for select to anon,authenticated using (is_active=true);
drop policy if exists theme_admin_write on public.theme_page_settings;
create policy theme_admin_write on public.theme_page_settings for all to authenticated using (private.is_admin()) with check (private.is_admin());

insert into public.theme_page_settings (website_key,page_key,page_name,component_tokens) values
('main','home','Home / Portfolio','{"hero":"portfolio","about":"portfolio","why_choose_us":"cards","catalogue":"catalogue","contact":"contact","footer":"footer"}'),
('cart','home','Customer Home','{"navbar":"header","hero":"hero","banner":"home_banner","offers":"live_offers","how_to_order":"steps","products":"catalogue","footer":"footer"}'),
('cart','products','Products / Catalogue','{"navbar":"header","search":"input","category_tabs":"pills","product_grid":"cards","product_card":"product_card","footer":"footer"}'),
('cart','cart','Cart','{"navbar":"header","cart_drawer":"drawer","cart_items":"cards","checkout":"checkout","footer":"footer"}'),
('cart','orders','My Orders','{"navbar":"header","order_list":"cards","status_badges":"badges","footer":"footer"}'),
('cart','tracker','Order Tracker','{"navbar":"header","timeline":"timeline","status_badges":"badges","footer":"footer"}'),
('cart','auth','Sign In / Account','{"navbar":"header","auth_card":"form_card","inputs":"input","buttons":"buttons"}'),
('cart','table','Price List','{"navbar":"header","table":"data_table","filters":"pills","footer":"footer"}'),
('cart','safety','Safety','{"navbar":"header","safety_cards":"cards","policy":"content_card","footer":"footer"}'),
('cart','transport','Shipping / Transport','{"navbar":"header","delivery_cards":"cards","schedule":"cards","footer":"footer"}'),
('cart','whatsapp','WhatsApp Ordering','{"navbar":"header","contact_card":"card","cta":"buttons","footer":"footer"}'),
('cart','mailing','Mailing Option','{"navbar":"header","mail_option":"card","cta":"buttons","footer":"footer"}'),
('cart','gift-boxes','Gift Boxes','{"navbar":"header","gift_grid":"cards","product_card":"product_card","footer":"footer"}'),
('cart','reviews','Customer Reviews','{"navbar":"header","review_cards":"cards","review_form":"form_card","footer":"footer"}'),
('admin','login','Admin Login','{"auth_card":"form_card","inputs":"input","buttons":"buttons"}'),
('admin','operations','Admin Operations','{"header":"admin_header","sidebar":"admin_nav","tables":"data_tables","cards":"cards","buttons":"buttons"}'),
('admin','banners','Banner Management','{"header":"admin_header","form":"form_card","media_upload":"upload","preview":"banner_preview","buttons":"buttons"}'),
('admin','company','Company Settings','{"header":"admin_header","form":"form_card","media_upload":"upload","buttons":"buttons"}'),
('admin','theme','Theme Control','{"header":"admin_header","theme_editor":"theme_editor","component_tokens":"component_controls","preview":"preview","buttons":"buttons"}'),
('admin','supabase','Supabase / Diagnostics','{"header":"admin_header","diagnostics":"data_cards","code":"code_panel"}'),
('mail','login','Mail Admin Login','{"auth_card":"mail_login","inputs":"input","buttons":"buttons"}'),
('mail','inbox','Mail Inbox / Workspace','{"sidebar":"mail_sidebar","mailboxes":"mailboxes","message_list":"message_list","reader":"message_reader","composer":"composer","buttons":"buttons"}')
on conflict (website_key,page_key) do update set page_name=excluded.page_name,component_tokens=excluded.component_tokens,updated_at=now();

-- Component-level editor: lets Admin target an exact path such as
-- Main / Portfolio -> Home -> About Us -> Heading.
create table if not exists public.theme_component_settings (
  theme_component_id bigint generated by default as identity primary key,
  website_key text not null,
  page_key text not null,
  section_key text not null,
  section_name text not null,
  component_key text not null,
  component_name text not null,
  component_type text not null default 'component',
  font_family text,
  font_size text,
  font_weight text,
  line_height text,
  letter_spacing text,
  text_color text,
  background_color text,
  border_color text,
  border_width text,
  border_radius text,
  box_shadow text,
  padding text,
  margin text,
  width text,
  max_width text,
  text_align text,
  component_tokens jsonb not null default '{}'::jsonb,
  content_value text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (website_key,page_key,section_key,component_key)
);
create index if not exists idx_theme_component_lookup on public.theme_component_settings(website_key,page_key,section_key,is_active,sort_order);
alter table public.theme_component_settings enable row level security;
revoke all on public.theme_component_settings from anon,authenticated;
grant select on public.theme_component_settings to anon,authenticated;
grant select,insert,update,delete on public.theme_component_settings to authenticated;
drop policy if exists theme_component_public_read on public.theme_component_settings;
create policy theme_component_public_read on public.theme_component_settings for select to anon,authenticated using (is_active=true);
drop policy if exists theme_component_admin_write on public.theme_component_settings;
create policy theme_component_admin_write on public.theme_component_settings for all to authenticated using (private.is_admin()) with check (private.is_admin());
create or replace function public.set_theme_component_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists trg_theme_component_updated_at on public.theme_component_settings;
create trigger trg_theme_component_updated_at before update on public.theme_component_settings for each row execute function public.set_theme_component_updated_at();
