-- RT Crackers Mail portal extension for the existing production Supabase project.
-- Safe to apply alongside the ecommerce schema. It does NOT replace or modify
-- products, orders, company_profile, offers, or customer tables.

do $$ begin
  create type public.mail_direction as enum ('inbound','outbound');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.mail_message_status as enum ('draft','queued','sent','delivered','failed','received','bounced','complained');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.mail_recipient_type as enum ('to','cc','bcc');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.mailbox_type as enum ('admin','system','support','sales','operations','billing','hr','general');
exception when duplicate_object then null; end $$;

create table if not exists public.business_email_purposes (
  email_purpose_id bigint generated by default as identity primary key,
  purpose_code varchar not null unique,
  purpose_name varchar not null
);

create table if not exists public.business_email_addresses (
  business_email_id bigint generated by default as identity primary key,
  email_purpose_id bigint not null references public.business_email_purposes(email_purpose_id),
  email_address varchar not null unique,
  display_name varchar,
  is_active boolean not null default true,
  is_public boolean not null default false,
  is_primary boolean not null default false
);

create table if not exists public.mailboxes (
  mailbox_id bigint generated by default as identity primary key,
  business_email_id bigint not null unique references public.business_email_addresses(business_email_id),
  business_id bigint not null default 1,
  email_address varchar not null unique check (email_address = lower(email_address)),
  local_part varchar not null,
  display_name varchar,
  mailbox_type public.mailbox_type not null default 'general',
  is_active boolean not null default true,
  is_receiving_enabled boolean not null default true,
  is_sending_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  account_id bigint
);

create table if not exists public.mailbox_access (
  mailbox_id bigint not null references public.mailboxes(mailbox_id) on delete cascade,
  auth_user_id uuid not null,
  access_level text not null default 'full',
  primary key (mailbox_id, auth_user_id)
);

create table if not exists public.email_messages (
  email_message_id bigint generated by default as identity primary key,
  mailbox_id bigint not null references public.mailboxes(mailbox_id),
  thread_id bigint,
  direction public.mail_direction not null,
  status public.mail_message_status not null default 'received',
  message_id text,
  in_reply_to text,
  references_header text,
  from_address varchar not null,
  from_name varchar,
  subject text,
  text_body text,
  html_body text,
  is_read boolean not null default false,
  is_starred boolean not null default false,
  sent_at timestamptz,
  received_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  resend_email_id text,
  resend_event_id text,
  folder text not null default 'inbox',
  snippet text
);

create unique index if not exists uq_email_messages_resend_email
  on public.email_messages (resend_email_id)
  where resend_email_id is not null;

create table if not exists public.email_recipients (
  email_recipient_id bigint generated by default as identity primary key,
  email_message_id bigint not null references public.email_messages(email_message_id) on delete cascade,
  recipient_type public.mail_recipient_type not null,
  email_address varchar not null check (email_address = lower(email_address)),
  display_name varchar,
  created_at timestamptz not null default now()
);

insert into public.business_email_purposes (purpose_code, purpose_name) values
 ('admin','Admin'),('noreply','No reply'),('sales','Sales'),('support','Support'),
 ('information','Info'),('orders','Orders'),('billing','Billing'),('contact','Contact'),('account','Account'),('help','Help')
on conflict (purpose_code) do update set purpose_name = excluded.purpose_name;

insert into public.business_email_addresses
  (email_purpose_id,email_address,display_name,is_active,is_public,is_primary)
select p.email_purpose_id, x.email_address, x.display_name, true, false, x.is_primary
from (values
 ('admin','admin@rtcrackers.com','RT Crackers Administration',true),
 ('sales','sales@rtcrackers.com','RT Crackers Sales',false),
 ('support','support@rtcrackers.com','RT Crackers Support',false),
 ('account','account@rtcrackers.com','RT Crackers Accounts',false),
 ('noreply','noreply@rtcrackers.com','RT Crackers No Reply',false),
 ('billing','billing@rtcrackers.com','RT Crackers Billing',false),
 ('contact','contact@rtcrackers.com','RT Crackers Contact',false),
 ('help','help@rtcrackers.com','RT Crackers Help',false),
 ('information','info@rtcrackers.com','RT Crackers Information',false),
 ('orders','orders@rtcrackers.com','RT Crackers Orders',false)
) as x(purpose_code,email_address,display_name,is_primary)
join public.business_email_purposes p on p.purpose_code=x.purpose_code
on conflict (email_address) do update
set display_name=excluded.display_name,
    is_active=true,
    is_primary=excluded.is_primary;

insert into public.mailboxes
  (business_email_id,business_id,email_address,local_part,display_name,mailbox_type)
select b.business_email_id,1,lower(b.email_address),lower(split_part(b.email_address,'@',1)),
       b.display_name,
       case p.purpose_code
         when 'admin' then 'admin'::public.mailbox_type
         when 'noreply' then 'system'::public.mailbox_type
         when 'sales' then 'sales'::public.mailbox_type
         when 'support' then 'support'::public.mailbox_type
         when 'orders' then 'operations'::public.mailbox_type
         when 'billing' then 'billing'::public.mailbox_type
         else 'general'::public.mailbox_type
       end
from public.business_email_addresses b
join public.business_email_purposes p using(email_purpose_id)
where b.is_active
on conflict (business_email_id) do update
set email_address=excluded.email_address,
    local_part=excluded.local_part,
    display_name=excluded.display_name,
    mailbox_type=excluded.mailbox_type,
    updated_at=now();


-- Production rule: only these ten RT Crackers addresses are used by the mail website.
update public.business_email_addresses
set is_active=false, is_primary=false
where email_address not in (
 'admin@rtcrackers.com','sales@rtcrackers.com','support@rtcrackers.com','account@rtcrackers.com',
 'noreply@rtcrackers.com','billing@rtcrackers.com','contact@rtcrackers.com','help@rtcrackers.com',
 'info@rtcrackers.com','orders@rtcrackers.com'
);

-- The existing production admin allow-list remains the authority.
-- Mailbox access can be granted later by inserting an auth user's UUID here.
alter table public.business_email_purposes enable row level security;
alter table public.business_email_addresses enable row level security;
alter table public.mailboxes enable row level security;
alter table public.mailbox_access enable row level security;
alter table public.email_messages enable row level security;
alter table public.email_recipients enable row level security;

revoke all on public.business_email_purposes from anon, authenticated;
revoke all on public.business_email_addresses from anon, authenticated;
revoke all on public.mailboxes from anon, authenticated;
revoke all on public.mailbox_access from anon, authenticated;
revoke all on public.email_messages from anon, authenticated;
revoke all on public.email_recipients from anon, authenticated;
