-- Test-only copy of the parts of your Supabase schema that the mail app touches.
drop table if exists email_recipients, email_messages, mailbox_access, mailboxes, admins,
  business_email_addresses, business_email_purposes cascade;
drop type if exists mail_direction, mail_message_status, mail_recipient_type, mailbox_type cascade;
create type mail_direction as enum ('inbound','outbound');
create type mail_message_status as enum ('draft','queued','sent','delivered','failed','received','bounced','complained');
create type mail_recipient_type as enum ('to','cc','bcc');
create type mailbox_type as enum ('admin','system','support','sales','operations','billing','hr','general');

create table business_email_purposes (email_purpose_id bigint generated by default as identity primary key,
  purpose_code varchar not null, purpose_name varchar not null);
create table business_email_addresses (business_email_id bigint generated by default as identity primary key,
  email_purpose_id bigint not null references business_email_purposes, email_address varchar not null,
  display_name varchar, is_active boolean not null default true);
create table mailboxes (mailbox_id bigint generated by default as identity primary key,
  business_email_id bigint not null unique references business_email_addresses, business_id bigint not null,
  email_address varchar not null unique check (email_address = lower(email_address)), local_part varchar not null,
  display_name varchar, mailbox_type mailbox_type not null default 'general', is_active boolean not null default true,
  is_receiving_enabled boolean not null default true, is_sending_enabled boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), account_id bigint);
create table admins (admin_id bigint generated by default as identity primary key, status text, auth_user_id uuid);
create table mailbox_access (mailbox_id bigint not null references mailboxes, auth_user_id uuid not null,
  access_level text not null default 'full', primary key (mailbox_id, auth_user_id));
create table email_messages (email_message_id bigint generated by default as identity primary key,
  mailbox_id bigint not null references mailboxes, thread_id bigint, direction mail_direction not null,
  status mail_message_status not null default 'received', message_id text, in_reply_to text, references_header text,
  from_address varchar not null, from_name varchar, subject text, text_body text, html_body text,
  is_read boolean not null default false, is_starred boolean not null default false, sent_at timestamptz,
  received_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, resend_email_id text, resend_event_id text, folder text not null default 'inbox', snippet text);
create unique index uq_email_messages_resend_email on email_messages (resend_email_id) where resend_email_id is not null;
create table email_recipients (email_recipient_id bigint generated by default as identity primary key,
  email_message_id bigint not null references email_messages on delete cascade, recipient_type mail_recipient_type not null,
  email_address varchar not null check (email_address = lower(email_address)), display_name varchar,
  created_at timestamptz not null default now());

insert into business_email_purposes (purpose_code, purpose_name) values
 ('admin','Admin'),('noreply','No reply'),('sales','Sales'),('support','Support'),('information','Info'),
 ('orders','Orders'),('billing','Billing'),('contact','Contact');
insert into business_email_addresses (email_purpose_id, email_address, display_name) values
 (1,'admin@rtcrackers.com','RT Crackers Administration'),(2,'noreply@rtcrackers.com','RT Crackers'),
 (3,'sales@rtcrackers.com','RT Crackers Sales'),(4,'support@rtcrackers.com','RT Crackers Support'),
 (5,'info@rtcrackers.com','RT Crackers Information'),(6,'orders@rtcrackers.com','RT Crackers Orders'),
 (7,'billing@rtcrackers.com','RT Crackers Billing');
-- mailbox rows for all but billing (billing is left out on purpose to test auto-provisioning)
insert into mailboxes (business_email_id, business_id, email_address, local_part, display_name)
 select business_email_id, 1, lower(email_address), split_part(lower(email_address),'@',1), display_name
 from business_email_addresses where split_part(email_address,'@',1) <> 'billing';
